config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  resources :charges
  resources :purchases, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/purchase.rb
class Purchase < ApplicationRecord
	after_create :email_purchaser

	def to_param
		uuid
	end

	def email_purchaser
		PurchaseMailer.purchase_receipt(self) .deliver
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	
	def create
	  product = Product.find(params[:product_id])
	  # Amount in cents

	  customer = Stripe::Customer.create(
	    :email => params[:stripeEmail],
	    :source  => params[:stripeToken],
	    :plan => product.sku
	  )

	  purchase = Purchase.create(email: params[:stripeEmail], card: params[:stripeToken], 
	  	amount: product.price_in_cents, description: product.description, currency: "usd",
	  	customer_id: customer.id, product_id: product.id, uuid: SecureRandom.uuid)

	  redirect_to purchase

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to new_charge_path
	end
end

app/controllers/pages_controller.rb
class PagesController <ApplicationController
	def home
		
	end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
	def show
		@purchase = Purchase.find_by_uuid(params[:id])
		@product = Product.find(@purchase.product_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/charges/create.html.erb
Thank you for your purchase!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, user-scalable=no">
  <title>LearnRailsPayments</title>
    <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,300,800' >
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="content" class="container">
    <header id="content-header">
        <%= image_tag('header-image.jpg', id:"content-head-img", alt: "Learn Rails!") %>
    </header>
    <%= yield %>
  </div>
  <footer id="site-footer">
Made by <a href="#" target="_blank">Learn App Code</a>
</footer>
  </body>
</html>

app/views/layouts/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/layouts/purchase_mail.html.erb
<!DOCTYPE html>
<html>
	<head> 
		<title>Your title</title>
	</head> 

	<body> 

		<%= yield %>
		<p> Thanks for your purchase! </p>

	</body> 
</html>

app/views/pages/home.html.erb
    <section id="content-details" class="row clearfix">
        <article id="details-article" class="col-sm-8">
            <h1 id="article-title"><%= @product.title %><span class="font-weight-light"><%= @product.subtitle %></span></h1>
           

        <%= raw @product.description %>
        </article>
        <aside id="details-aside" class="col-sm-4">


                            <%= form_tag charges_path, id:'chargeForm' do %>

                    <% if flash[:error].present? %>
                      <div id="error_explanation">
                        <p><%= flash[:error] %></p>
                      </div>
                    <% end %>

                  <script src="https://checkout.stripe.com/checkout.js"></script>
                  <%= hidden_field_tag 'stripeToken' %>
                  <%= hidden_field_tag 'amount', @product.price_in_cents %>
                  <%= hidden_field_tag 'stripeEmail' %>
                  <button id="btn-buy" type="button" class="btn btn-success btn-lg btn-block"><span class="glyphicon glyphicon-ok"></span>Buy this!</button>
<script>
    var handler = StripeCheckout.configure({
      key: '<%= Rails.configuration.stripe[:publishable_key] %>',
      token: function(token, arg) {
        document.getElementById("stripeToken").value = token.id;
        document.getElementById("stripeEmail").value = token.email;
        document.getElementById("chargeForm").submit();
      }
});
document.getElementById('btn-buy').addEventListener('click', function(e) {
      handler.open({
        name: 'Learn Rails',
        description: '<%= @product.title %> ($<%= @product.price %>)',
        amount: document.getElementById("amount").value
    });
    e.preventDefault();
   })
</script>
<% end %>
            <ul id="details-infobox" class="list-group">
              <li class="list-group-item active clearfix">Info</li>
              <li class="list-group-item"><%= @product.info %></li>
            </ul>
        </aside>
    </section>

app/views/products/index.html.erb
<section id="content-details" class="row clearfix">
  <article id="details-article" class="col-sm-8">
    <h1 id="article-title">Look at our animals!</h1>
  </article>
</section>

<section id="products">
<% @products.each do |product| %>
 <div class="product clearfix">
   <a href="<%= product_path(product) %>">
    <div class="product-image-container">
     <img src="<%= asset_path product.image_name %>"  alt="<%= product.title %>"/>
     <span class="product-price">$<%= product.price %></span>
   </div>
   <p class="product-title"><%= product.title %></p></a>
 </div>
 <% end %>
</section>

app/views/products/show.html.erb
    <section id="content-details" class="row clearfix">
        <article id="details-article" class="col-sm-8">
            <h1 id="article-title"><%= @product.title %><span class="font-weight-light"><%= @product.subtitle %></span></h1>
           

        <%= raw @product.description %>
        </article>
        <aside id="details-aside" class="col-sm-4">


                            <%= form_tag charges_path, id:'chargeForm' do %>

                    <% if flash[:error].present? %>
                      <div id="error_explanation">
                        <p><%= flash[:error] %></p>
                      </div>
                    <% end %>

                  <script src="https://checkout.stripe.com/checkout.js"></script>
                  <%= hidden_field_tag 'stripeToken' %>
                  <%= hidden_field_tag 'amount', @product.price_in_cents %>
                  <%= hidden_field_tag 'stripeEmail' %>
                  <%= hidden_field_tag 'product_id', @product.id %>
                  <button id="btn-buy" type="button" class="btn btn-success btn-lg btn-block"><span class="glyphicon glyphicon-ok"></span>Buy this!</button>
<script>
    var handler = StripeCheckout.configure({
      key: '<%= Rails.configuration.stripe[:publishable_key] %>',
      token: function(token, arg) {
        document.getElementById("stripeToken").value = token.id;
        document.getElementById("stripeEmail").value = token.email;
        document.getElementById("chargeForm").submit();
      }
});
document.getElementById('btn-buy').addEventListener('click', function(e) {
      handler.open({
        name: 'Learn Rails',
        description: '<%= @product.title %> ($<%= @product.price %>)',
        amount: document.getElementById("amount").value
    });
    e.preventDefault();
   })
</script>
<% end %>
            <ul id="details-infobox" class="list-group">
              <li class="list-group-item active clearfix">Info</li>
              <li class="list-group-item"><%= @product.info %></li>
            </ul>
        </aside>
    </section>

app/views/purchases/show.html.erb
   <section id="content-receipt" class="clearfix">
      <div id="receipt-container">
        <div class="dotmatrix left"></div>
        <div id="receipt-content">
          <h4 id="receipt-title">Thank You!</h4>
          <p><strong>RECEIPT</strong></p>
          <div id="receipt-details" class="row clearfix">
            <div class="col-sm-8 receipt-left">
              <p><strong class="font-weight-heavy"><%= @product.title %></strong><br/> <span class="font-weight-light"><%= @product.subtitle %></span></p>
            </div>
            <div class="col-sm-4">
             $<%= @product.price %>
            </div>
          </div>

          <a href="https://s3-us-west-2.amazonaws.com/rails-learnapp-bucket/kitty.JPG"><button type="button" class="btn btn-success btn-xs">DOWNLOAD</button></a>
          <footer id="receipt-footer">
            <small>Your purchase is complete. We hope you enjoy it!</small>
          </footer>
        </div>
        <div class="dotmatrix right"></div>
      </div>
      <div id="receipt-shadow"></div>
    </section>